name: Node.js CI - with cache - composite
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Build Node
        uses: merlusorg/GHA.workflows/.github/actions/build-node@main